version: '3.1'

services:
    flask_om:
        container_name: flask_om
        build: app
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - ./app:/app
        networks:
            - flask_om

    mysql-db:
        container_name: mysql_flask_om
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - flask_om

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

networks:
    flask_om:

volumes:
    app:
    database:
